# based on https://github.com/Arcnor/MiyooCFW/blob/ci/.github/workflows/main.yml
name: Build

# Run on changes (including automated ones from the update job), allow manual triggering from the Actions tab, and allow triggering from update job
on: [push, pull_request, workflow_dispatch, workflow_call]

# todo: figure out how to use reusable workflows or actions or something to reduce the amount of
# duplication between this and the submodule's build configurations

jobs:

  # https://github.com/MiyooCFW/uboot/blob/master/.github/workflows/main.yml
  uboot:
    runs-on: ubuntu-20.04
    container:
      image: miyoocfw/toolchain:master
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule update --init --recursive -- uboot
        cd uboot
        make miyoo_defconfig 
        make
    - uses: actions/upload-artifact@v2
      with:
        name: uboot
        path: uboot/u-boot-sunxi-with-spl.bin
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`

  # https://github.com/MiyooCFW/sdcard/blob/master/.github/workflows/build.yml
  boot-scr:
    runs-on: ubuntu-20.04
    container:
      image: miyoocfw/toolchain:master
    steps:
    - uses: actions/checkout@v3
    - run: |
        git submodule update --init --recursive -- sdcard
        cd sdcard
        ./gen_boot_scr.sh
    - uses: actions/upload-artifact@v2
      with:
        name: boot-scr
        path: sdcard/boot/boot.scr
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`

  # https://github.com/MiyooCFW/kernel/blob/master/.github/workflows/c-cpp.yml
  # todo: 1-bit sd card variant
  kernel:
    runs-on: ubuntu-20.04
    container:
      image: miyoocfw/toolchain:master
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule update --init --recursive -- kernel
        cd kernel
        make miyoo_defconfig 
        make zImage
        make M=$PwD
        mkdir dist
        mv arch/arm/boot/dts/suniv-f1c500s-miyoo.dtb dist/
        mv arch/arm/boot/zImage dist/
        mv drivers/video/fbdev/core/*.ko dist/
        mv drivers/video/fbdev/r61520fb.ko dist/
    - uses: actions/upload-artifact@v2
      with:
        name: kernel
        path: kernel/dist/*
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
        
  # todo: use buildroot for more than just the rootfs
  buildroot:
    runs-on: ubuntu-20.04
    container:
      image: miyoocfw/toolchain:master
    env:
      FORCE_UNSAFE_CONFIGURE: 1
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule update --init --recursive -- buildroot
        cd buildroot
        make
        cd output/images/
        xz rootfs.tar
        ls -l
    - uses: actions/upload-artifact@v2
      with:
        name: buildroot
        path: buildroot/output/images/rootfs.tar.xz
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`

  # https://github.com/MiyooCFW/logo/blob/master/.github/workflows/c-cpp.yml
  # todo: bittboy and pocketgo logos
  logo:
    runs-on: ubuntu-20.04
    container:
      image: miyoocfw/toolchain:master
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule update --init --recursive -- logo
        cd logo
        make -f Makefile.powkiddy
    - uses: actions/upload-artifact@v2
      with:
        name: boot-logo-powkiddy
        path: logo/boot-logo
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`

  # https://github.com/MiyooCFW/daemon/blob/master/.github/workflows/c-cpp.yml
  daemon:
    runs-on: ubuntu-20.04
    container:
      image: miyoocfw/toolchain:master
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule update --init --recursive -- daemon
        cd daemon
        make
    - uses: actions/upload-artifact@v2
      with:
        name: daemon
        path: daemon/daemon
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
        
  # todo: submodule and build miyooctl, then copy it into the sdcard

  # https://github.com/MiyooCFW/gmenunx/blob/master/.github/workflows/c-cpp.yml
  gmenunx:
    runs-on: ubuntu-20.04
    container:
      image: miyoocfw/toolchain:master
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule update --init --recursive -- gmenunx
        cd gmenunx
        make -f Makefile.miyoo dist
    - uses: actions/upload-artifact@v2
      with:
        name: gmenunx
        path: gmenunx/dist/miyoo/GMenuNX.zip
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
        
  build-image:
    needs: 
    - uboot
    - boot-scr
    - kernel
    - buildroot
    - logo
    - daemon
    - gmenunx
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "::set-output name=version::$GITHUB_REF_NAME-$(git rev-parse --short HEAD)"
      id: version
    - run: echo "Version ${{ steps.version.outputs.version }}"
    - uses: actions/download-artifact@v3
    - run: find .
    - name: Replace files under sdcard with the ones we just built
      run: |
        # start with our "sdcard" submodule source, which contains precompiled things and a script
        # to assemble it into an image
        git submodule update --init --recursive -- sdcard
        
        # overwrite some of the precompiled files with the artefacts we just built
        # todo: figure out a good way to differentiate between things we replace and the things we don't
        mv uboot/u-boot-sunxi-with-spl.bin sdcard/boot/misc/u-boot-bins/u-boot-v90_q90_pocketgo.bin
        mv boot-scr/boot.scr sdcard/boot/boot.scr
        mv kernel/suniv-f1c500s-miyoo.dtb sdcard/boot/
        mv kernel/zImage sdcard/boot/variants/v90_q90/
        mv kernel/*.ko sdcard/boot/variants/v90_q90/
        mv buildroot/rootfs.tar.xz sdcard/rootfs.tar.xz 
        mv boot-logo-powkiddy/boot-logo sdcard/boot/variants/v90_q90/
        mv daemon/daemon sdcard/boot/variants/v90_q90/
        unzip -o gmenunx/GMenuNX.zip -d sdcard/main/
        
        # todo: other variants
    - run: find .
    
    # https://github.com/MiyooCFW/sdcard/blob/master/.github/workflows/build.yml
    - name: Build image
      run: |
          cd sdcard
          export VERSION=${{ steps.version.outputs.version }}
          sudo ./generate_image_file.sh
    - uses: actions/upload-artifact@v2
      with:
        name: "cfw-${{ steps.version.outputs.version }}.img"
        path: sdcard/cfw-*.img
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`

  # Currently, if the uboot built from source is used, then we don't get video
  # and, if the rootfs built by buildroot is used, then we can't boot at all.
  # So, this is a temporary image that omits those two sources and uses the older 
  # content from the sdcard repo instead. We'll get rid of this eventually.
  build-mixed-image:
    needs: 
    - boot-scr
    - kernel
    - logo
    - daemon
    - gmenunx
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "::set-output name=version::$GITHUB_REF_NAME-$(git rev-parse --short HEAD)-mixed"
      id: version
    - run: echo "Version ${{ steps.version.outputs.version }}"
    - uses: actions/download-artifact@v3
    - run: find .
    - name: Replace files under sdcard with the ones we just built
      run: |
        # start with our "sdcard" submodule source
        git submodule update --init --recursive -- sdcard
        
        # overwrite some of it's files with (some of) the artefacts we just built
        mv boot-scr/boot.scr sdcard/boot/boot.scr
        mv kernel/suniv-f1c500s-miyoo.dtb sdcard/boot/
        mv kernel/zImage sdcard/boot/variants/v90_q90/
        mv kernel/*.ko sdcard/boot/variants/v90_q90/
        mv boot-logo-powkiddy/boot-logo sdcard/boot/variants/v90_q90/
        mv daemon/daemon sdcard/boot/variants/v90_q90/
        unzip -o gmenunx/GMenuNX.zip -d sdcard/main/
  
    - run: find .
    
    # https://github.com/MiyooCFW/sdcard/blob/master/.github/workflows/build.yml
    - name: Build image
      run: |
          cd sdcard
          export VERSION=${{ steps.version.outputs.version }}
          sudo ./generate_image_file.sh
    - uses: actions/upload-artifact@v2
      with:
        name: "cfw-${{ steps.version.outputs.version }}.img"
        path: sdcard/cfw-*.img
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
