name: Update & Build

on:
  # Run nightly: 8am UTC = 3am Eastern
  schedule:
  - cron: '0 8 * * *'
  # Or run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-submodules:
    # only run on the main repo; forks can pull changes from there
    if: github.repository == 'TriForceX/MiyooCFW'
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      changes: ${{ steps.update.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
      - name: Update all submodules
        id: update
        run: |
          # initialize submodules at their current local version
          git submodule update --init --recursive
          
          # update submodules to the latest remote version
          git submodule update --remote --merge
          
          # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs
          echo "::set-output name=changes::$(git status --porcelain)"
      - name: Push changes
        if: ${{ steps.update.outputs.changes }}
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Actions"
          git commit -am "Updated submodules $(date)"
          git push
  # note: the git push in the update submodules step uses the built-in GITHUB_TOKEN, which is not allowed to trigger
  # other workflows, such as our build.yml, so we have to call it explicitly here.
  build:
    needs: update-submodules
    if: ${{ needs.update-submodules.outputs.changes}}
    uses: ./.github/workflows/build.yml
